spring:
  application:
    name: umtle-api
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: when-authorized

logging:
  level:
    org.hibernate.SQL: debug
  pattern:
    level: "%5p [%X{traceId:-}]"
