ALTER TABLE students
    ADD COLUMN phone VARCHAR(20) NULL,
    ADD COLUMN birth_date DATE NULL,
    ADD COLUMN school VARCHAR(100) NULL,
    ADD COLUMN grade VARCHAR(20) NULL,
    ADD COLUMN memo VARCHAR(1000) NULL;
